version: '3.8'
services:
    db:
        image: postgres:16-bookworm
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123123
            POSTGRES_DB: mydb
        ports:
            - '5432:5432'
    redis:
        image: redis:7-bookworm
        ports:
            - '6379:6379'
    image_server:
        image: python:3.11-alpine
        build: ./ImageBackend
        environment:
            - 'secret_key: hehehehe'
        ports:
            - '5787:5787'
        volumes:
            - './image_app:/usr/src/app/upload'